---
- name: add php5.5 repo
  apt_repository: repo='ppa:ondrej/php5'

- name: install php 5.5
  apt: pkg=php5 update_cache=yes

- name: install php-fpm
  apt: name=php5-fpm state=installed

- name: php install needed modules
  apt: name={{ item }} state=installed
  with_items:
    - php5-common
    - php5-curl
    - php5-gd
    - php5-mysql

- name: service run php5-fpm
  action: service name=php5-fpm state=started

- name: fpm config
  template: src='php-fpm/templates/www.conf' dest='/etc/php5/fpm/pool.d/www.conf'
  notify:
    - restart php5-fpm
